export interface Surah {
  id: number;
  name: string;
  aliases?: string[];
}

export const mockSurahs: Surah[] = [
  { id: 1, name: "Al-Fatihah", aliases: ["The Opening", "Fatiha", "The Key"] },
  { id: 2, name: "Al-Baqarah", aliases: ["The Cow", "Baqara", "Bakra"] },
  { id: 3, name: "Ali 'Imran", aliases: ["The Family of Imran", "Amran", "Imran"] },
  { id: 4, name: "An-Nisa", aliases: ["The Women", "Nisa"] },
  { id: 5, name: "Al-Ma'idah", aliases: ["The Table", "Maida", "Jesus", "Isa", "Eesa"] },
  { id: 6, name: "Al-An'am", aliases: ["The Cattle", "Anam"] },
  { id: 7, name: "Al-A'raf", aliases: ["The Heights", "Araf"] },
  { id: 8, name: "Al-Anfal", aliases: ["The Spoils of War", "Anfal"] },
  { id: 9, name: "At-Tawbah", aliases: ["The Repentance", "Tawbah"] },
  { id: 10, name: "Yunus", aliases: ["Jonah", "Yunus"] },
  { id: 11, name: "Hud", aliases: ["Hud"] },
  { id: 12, name: "Yusuf", aliases: ["Joseph", "Yusuf"] },
  { id: 13, name: "Ar-Ra'd", aliases: ["The Thunder", "Raad"] },
  { id: 14, name: "Ibrahim", aliases: ["Abraham", "Ibrahim"] },
  { id: 15, name: "Al-Hijr", aliases: ["The Rocky Tract", "Hijr"] },
  { id: 16, name: "An-Nahl", aliases: ["The Bee", "Nahl"] },
  { id: 17, name: "Al-Isra", aliases: ["The Night Journey", "Isra", "Bani Israil"] },
  { id: 18, name: "Al-Kahf", aliases: ["The Cave", "Kahf"] },
  { id: 19, name: "Maryam", aliases: ["Mary", "Jesus", "Isa", "Eesa"] },
  { id: 20, name: "Ta-Ha", aliases: ["Taha"] },
  { id: 21, name: "Al-Anbiya", aliases: ["The Prophets", "Anbiya"] },
  { id: 22, name: "Al-Hajj", aliases: ["The Pilgrimage", "Hajj"] },
  { id: 23, name: "Al-Mu'minun", aliases: ["The Believers", "Muminun"] },
  { id: 24, name: "An-Nur", aliases: ["The Light", "Nur"] },
  { id: 25, name: "Al-Furqan", aliases: ["The Criterion", "Furqan"] },
  { id: 26, name: "Ash-Shu'ara", aliases: ["The Poets", "Shuara"] },
  { id: 27, name: "An-Naml", aliases: ["The Ant", "Naml"] },
  { id: 28, name: "Al-Qasas", aliases: ["The Stories", "Qasas"] },
  { id: 29, name: "Al-Ankabut", aliases: ["The Spider", "Ankabut"] },
  { id: 30, name: "Ar-Rum", aliases: ["The Romans", "Rum"] },
  { id: 31, name: "Luqman", aliases: ["Luqman"] },
  { id: 32, name: "As-Sajdah", aliases: ["The Prostration", "Sajdah"] },
  { id: 33, name: "Al-Ahzab", aliases: ["The Combined Forces", "Ahzab"] },
  { id: 34, name: "Saba", aliases: ["Sheba", "Saba"] },
  { id: 35, name: "Fatir", aliases: ["The Originator", "Fatir"] },
  { id: 36, name: "Ya-Sin", aliases: ["Yasin", "Yaseen"] },
  { id: 37, name: "As-Saffat", aliases: ["Those who set the Ranks", "Saffat"] },
  { id: 38, name: "Sad", aliases: ["Sad"] },
  { id: 39, name: "Az-Zumar", aliases: ["The Troops", "Zumar"] },
  { id: 40, name: "Ghafir", aliases: ["The Forgiver", "Ghafir", "Al-Mumin"] },
  { id: 67, name: "Al-Mulk", aliases: ["The Kingdom", "Mulk", "Tabarak"] },
  { id: 112, name: "Al-Ikhlas", aliases: ["The Sincerity", "Purity", "Tauheed", "Monotheism"] },
  { id: 113, name: "Al-Falaq", aliases: ["The Daybreak", "Falaq"] },
  { id: 114, name: "An-Nas", aliases: ["Mankind", "Nas"] },
];
