export interface Surah {
  id: number;
  name: string;
  aliases?: string[];
}

export const mockSurahs: Surah[] = [
  { id: 1, name: "Al-Fatihah", aliases: ["The Opening", "Fatiha", "The Key"] },
  { id: 2, name: "Al-Baqarah", aliases: ["The Cow", "Baqara", "Bakra"] },
  { id: 3, name: "Ali 'Imran", aliases: ["The Family of Imran", "Amran", "Imran"] },
  { id: 4, name: "An-Nisa", aliases: ["The Women", "Nisa"] },
  { id: 5, name: "Al-Ma'idah", aliases: ["The Table", "Maida", "Jesus", "Isa", "Eesa"] },
  { id: 6, name: "Al-An'am", aliases: ["The Cattle", "Anam"] },
  { id: 7, name: "Al-A'raf", aliases: ["The Heights", "Araf"] },
  { id: 8, name: "Al-Anfal", aliases: ["The Spoils of War", "Anfal"] },
  { id: 9, name: "At-Tawbah", aliases: ["The Repentance", "Tawbah"] },
  { id: 10, name: "Yunus", aliases: ["Jonah", "Yunus"] },
  { id: 11, name: "Hud", aliases: ["Hud"] },
  { id: 12, name: "Yusuf", aliases: ["Joseph", "Yusuf"] },
  { id: 13, name: "Ar-Ra'd", aliases: ["The Thunder", "Raad"] },
  { id: 14, name: "Ibrahim", aliases: ["Abraham", "Ibrahim"] },
  { id: 15, name: "Al-Hijr", aliases: ["The Rocky Tract", "Hijr"] },
  { id: 16, name: "An-Nahl", aliases: ["The Bee", "Nahl"] },
  { id: 17, name: "Al-Isra", aliases: ["The Night Journey", "Isra", "Bani Israil"] },
  { id: 18, name: "Al-Kahf", aliases: ["The Cave", "Kahf"] },
  { id: 19, name: "Maryam", aliases: ["Mary", "Jesus", "Isa", "Eesa"] },
  { id: 20, name: "Ta-Ha", aliases: ["Taha"] },
  { id: 21, name: "Al-Anbiya", aliases: ["The Prophets", "Anbiya"] },
  { id: 22, name: "Al-Hajj", aliases: ["The Pilgrimage", "Hajj"] },
  { id: 23, name: "Al-Mu'minun", aliases: ["The Believers", "Muminun"] },
  { id: 24, name: "An-Nur", aliases: ["The Light", "Nur"] },
  { id: 25, name: "Al-Furqan", aliases: ["The Criterion", "Furqan"] },
  { id: 26, name: "Ash-Shu'ara", aliases: ["The Poets", "Shuara"] },
  { id: 27, name: "An-Naml", aliases: ["The Ant", "Naml"] },
  { id: 28, name: "Al-Qasas", aliases: ["The Stories", "Qasas"] },
  { id: 29, name: "Al-Ankabut", aliases: ["The Spider", "Ankabut"] },
  { id: 30, name: "Ar-Rum", aliases: ["The Romans", "Rum"] },
  { id: 31, name: "Luqman", aliases: ["Luqman"] },
  { id: 32, name: "As-Sajdah", aliases: ["The Prostration", "Sajdah"] },
  { id: 33, name: "Al-Ahzab", aliases: ["The Combined Forces", "Ahzab"] },
  { id: 34, name: "Saba", aliases: ["Sheba", "Saba"] },
  { id: 35, name: "Fatir", aliases: ["The Originator", "Fatir"] },
  { id: 36, name: "Ya-Sin", aliases: ["Yasin", "Yaseen"] },
  { id: 37, name: "As-Saffat", aliases: ["Those who set the Ranks", "Saffat"] },
  { id: 38, name: "Sad", aliases: ["Sad"] },
  { id: 39, name: "Az-Zumar", aliases: ["The Troops", "Zumar"] },
  { id: 40, name: "Ghafir", aliases: ["The Forgiver", "Ghafir", "Al-Mumin"] },
  { id: 41, name: "Fussilat", aliases: ["Explained in Detail", "Fussilat", "Ha Mim Sajdah"] },
  { id: 42, name: "Ash-Shura", aliases: ["The Consultation", "Shura"] },
  { id: 43, name: "Az-Zukhruf", aliases: ["The Ornaments of Gold", "Zukhruf"] },
  { id: 44, name: "Ad-Dukhan", aliases: ["The Smoke", "Dukhan"] },
  { id: 45, name: "Al-Jathiyah", aliases: ["The Crouching", "Jathiyah"] },
  { id: 46, name: "Al-Ahqaf", aliases: ["The Wind-Curved Sandhills", "Ahqaf"] },
  { id: 47, name: "Muhammad", aliases: ["Muhammad", "Muhammed"] },
  { id: 48, name: "Al-Fath", aliases: ["The Victory", "Fath"] },
  { id: 49, name: "Al-Hujurat", aliases: ["The Dwellings", "Hujurat"] },
  { id: 50, name: "Qaf", aliases: ["Qaf"] },
  { id: 51, name: "Adh-Dhariyat", aliases: ["The Winnowing Winds", "Dhariyat"] },
  { id: 52, name: "At-Tur", aliases: ["The Mount", "Tur"] },
  { id: 53, name: "An-Najm", aliases: ["The Star", "Najm"] },
  { id: 54, name: "Al-Qamar", aliases: ["The Moon", "Qamar"] },
  { id: 55, name: "Ar-Rahman", aliases: ["The Beneficent", "Rahman"] },
  { id: 56, name: "Al-Waqi'ah", aliases: ["The Inevitable", "Waqiah"] },
  { id: 57, name: "Al-Hadid", aliases: ["The Iron", "Hadid"] },
  { id: 58, name: "Al-Mujadila", aliases: ["The Pleading Woman", "Mujadilah"] },
  { id: 59, name: "Al-Hashr", aliases: ["The Exile", "Hashr"] },
  { id: 60, name: "Al-Mumtahanah", aliases: ["She that is to be examined", "Mumtahanah"] },
  { id: 61, name: "As-Saff", aliases: ["The Ranks", "Saff"] },
  { id: 62, name: "Al-Jumu'ah", aliases: ["The Congregation", "Jumuah"] },
  { id: 63, name: "Al-Munafiqun", aliases: ["The Hypocrites", "Munafiqun"] },
  { id: 64, name: "At-Taghabun", aliases: ["The Mutual Disillusion", "Taghabun"] },
  { id: 65, name: "At-Talaq", aliases: ["The Divorce", "Talaq"] },
  { id: 66, name: "At-Tahrim", aliases: ["The Prohibition", "Tahrim"] },
  { id: 67, name: "Al-Mulk", aliases: ["The Kingdom", "Mulk", "Tabarak"] },
  { id: 68, name: "Al-Qalam", aliases: ["The Pen", "Qalam"] },
  { id: 69, name: "Al-Haqqah", aliases: ["The Inevitable", "Haqqah"] },
  { id: 70, name: "Al-Ma'arij", aliases: ["The Ascending Stairways", "Maarij"] },
  { id: 71, name: "Nuh", aliases: ["Noah", "Nuh"] },
  { id: 72, name: "Al-Jinn", aliases: ["The Jinn", "Jinn"] },
  { id: 73, name: "Al-Muzzammil", aliases: ["The Enshrouded One", "Muzzammil"] },
  { id: 74, name: "Al-Muddaththir", aliases: ["The Cloaked One", "Muddaththir"] },
  { id: 75, name: "Al-Qiyamah", aliases: ["The Resurrection", "Qiyamah"] },
  { id: 76, name: "Al-Insan", aliases: ["The Man", "Insan"] },
  { id: 77, name: "Al-Mursalat", aliases: ["The Emissaries", "Mursalat"] },
  { id: 78, name: "An-Naba", aliases: ["The Tidings", "Naba"] },
  { id: 79, name: "An-Nazi'at", aliases: ["Those who drag forth", "Naziat"] },
  { id: 80, name: "Abasa", aliases: ["He Frowned", "Abasa"] },
  { id: 81, name: "At-Takwir", aliases: ["The Overthrowing", "Takwir"] },
  { id: 82, name: "Al-Infitar", aliases: ["The Cleaving", "Infitar"] },
  { id: 83, name: "Al-Mutaffifin", aliases: ["The Defrauding", "Mutaffifin"] },
  { id: 84, name: "Al-Inshiqaq", aliases: ["The Sundering", "Inshiqaq"] },
  { id: 85, name: "Al-Buruj", aliases: ["The Mansions of the Stars", "Buruj"] },
  { id: 86, name: "At-Tariq", aliases: ["The Nightcomer", "Tariq"] },
  { id: 87, name: "Al-A'la", aliases: ["The Most High", "Ala"] },
  { id: 88, name: "Al-Ghashiyah", aliases: ["The Overwhelming", "Ghashiyah"] },
  { id: 89, name: "Al-Fajr", aliases: ["The Dawn", "Fajr"] },
  { id: 90, name: "Al-Balad", aliases: ["The City", "Balad"] },
  { id: 91, name: "Ash-Shams", aliases: ["The Sun", "Shams"] },
  { id: 92, name: "Al-Lail", aliases: ["The Night", "Lail"] },
  { id: 93, name: "Ad-Duha", aliases: ["The Morning Hours", "Duha"] },
  { id: 94, name: "Ash-Sharh", aliases: ["The Relief", "Sharh"] },
  { id: 95, name: "At-Tin", aliases: ["The Fig", "Tin"] },
  { id: 96, name: "Al-Alaq", aliases: ["The Clot", "Alaq"] },
  { id: 97, name: "Al-Qadr", aliases: ["The Power", "Qadr"] },
  { id: 98, name: "Al-Bayyinah", aliases: ["The Clear Proof", "Bayyinah"] },
  { id: 99, name: "Az-Zalzalah", aliases: ["The Earthquake", "Zalzalah"] },
  { id: 100, name: "Al-Adiyat", aliases: ["The Courser", "Adiyat"] },
  { id: 101, name: "Al-Qari'ah", aliases: ["The Calamity", "Qariah"] },
  { id: 102, name: "At-Takathur", aliases: ["The Rivalry in World Increase", "Takathur"] },
  { id: 103, name: "Al-Asr", aliases: ["The Declining Day", "Asr"] },
  { id: 104, name: "Al-Humazah", aliases: ["The Traducer", "Humazah"] },
  { id: 105, name: "Al-Fil", aliases: ["The Elephant", "Fil"] },
  { id: 106, name: "Quraish", aliases: ["Quraish"] },
  { id: 107, name: "Al-Ma'un", aliases: ["The Small Kindnesses", "Maun"] },
  { id: 108, name: "Al-Kauthar", aliases: ["The Abundance", "Kauthar"] },
  { id: 109, name: "Al-Kafirun", aliases: ["The Disbelievers", "Kafirun"] },
  { id: 110, name: "An-Nasr", aliases: ["The Divine Support", "Nasr"] },
  { id: 111, name: "Al-Masad", aliases: ["The Palm Fiber", "Masad"] },
  { id: 112, name: "Al-Ikhlas", aliases: ["The Sincerity", "Purity", "Tauheed", "Monotheism"] },
  { id: 113, name: "Al-Falaq", aliases: ["The Daybreak", "Falaq"] },
  { id: 114, name: "An-Nas", aliases: ["Mankind", "Nas"] },
];
